name: tests/fast

on:
  push:
    branches:
        - v4.2

  pull_request:
    branches:
        - v4.2

env:
  DOTNET_VERSION: 3.1.420
  DOTNET_VERSION_6: 6.0.301

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ ubuntu-latest, windows-latest ]
        fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION_6 }}

    - name: Install dependencies
      run: |
        dotnet tool install -g trx2junit
        dotnet restore

    - name: Test - Release
      run: dotnet test --configuration Debug --no-restore --logger "trx;verbosity=detailed" --logger "console;verbosity=detailed" --results-directory "./"
      env: # Or as an environment variable
        RAVEN_LICENSE: ${{ secrets.RAVEN_LICENSE }}
        RAVEN_MAX_RUNNING_TESTS: 1
      working-directory: ./test/FastTests

    - name: Convert tests
      run: trx2junit ./*.trx
      if: always()
      working-directory: ./test/FastTests

    - name: Publish Unit Test Results - Ubuntu
      uses: EnricoMi/publish-unit-test-result-action@v1.35
      if: ${{ always() && contains(matrix.os, 'ubuntu') }}
      with:
        files: "./test/FastTests/*.xml"
    - name: Publish Unit Test Results - Windows
      uses: EnricoMi/publish-unit-test-result-action/composite@v1.35
      if: ${{ always() && contains(matrix.os, 'windows') }}
      with:
        files: "./test/FastTests/*.xml"

  debug:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ ubuntu-latest, windows-latest ]
        fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION_6 }}

    - name: Install dependencies
      run: |
        dotnet tool install -g trx2junit
        dotnet restore

    - name: Test - Debug
      run: dotnet test --configuration Debug --no-restore --logger "trx;verbosity=detailed" --logger "console;verbosity=detailed" --results-directory "./"
      env: # Or as an environment variable
        RAVEN_LICENSE: ${{ secrets.RAVEN_LICENSE }}
        RAVEN_MAX_RUNNING_TESTS: 1
      working-directory: ./test/FastTests

    - name: Convert tests
      run: trx2junit ./*.trx
      if: always()
      working-directory: ./test/FastTests

    - name: Publish Unit Test Results - Ubuntu
      uses: EnricoMi/publish-unit-test-result-action@v1.35
      if: ${{ always() && contains(matrix.os, 'ubuntu') }}
      with:
        files: "./test/FastTests/*.xml"
    - name: Publish Unit Test Results - Windows
      uses: EnricoMi/publish-unit-test-result-action/composite@v1.35
      if: ${{ always() && contains(matrix.os, 'windows') }}
      with:
        files: "./test/FastTests/*.xml"
